export enum ActionType {
  SEARCH_ARTIST_SUCCESS = "SEARCH_ARTIST_SUCCESS",
  SEARCH_ARTIST_ERROR = "SEARCH_ARTIST_ERROR",
  GET_MORE_ARTIST_PAYLOAD_SUCCESS = "GET_MORE_ARTIST_PAYLOAD_SUCCESS",
  GET_MORE_ARTIST_PAYLOAD_ERROR = "GET_MORE_ARTIST_PAYLOAD_ERROR",
  GET_ALBUM_DETAIL_SUCCESS = "GET_ALBUM_DETAIL_SUCCESS",
  GET_ALBUM_DETAIL_FAILED = "GET_ALBUM_DETAIL_FAILED",
}
export default ActionType;
